sudo: false

language: node_js
node_js:
  - "6.9.4"

before_install:
- export LANG=en_US.UTF-8
- npm install -g npm@3.10.10
- npm install -g karma-cli cordova ionic

install:
- npm install

script:
- npm run test-ci